"""
Outcome-independent coverage resolution.

`coverage_map.json` (generated by `build_coverage_map.py`) declares, for every attack
subfamily, which of V2's three declared input controls -- length / strict_type_schema /
normalization -- is *intended* to govern it, derived from the attack construction and the
control design, **never** from observed V1/V2 results. This is the formal answer to the
jury's circularity concern: it says up front which cases the defenses were built to address
and which test behaviour outside those controls.

The four classes (definitions, pending Ahsan's confirmation as clarifications of CONTRACTS
6.5 -- the class *names* are frozen in contract.py):

  in_scope      the constructed condition is directly governed by at least one declared
                input control, if/when it reaches that control.
  not_targeted  a valid, schema-conformant text request whose relevant behaviour no
                declared control was designed to alter or reject (effect, if any, is model-level).
  out_of_scope  the condition occurs at the transport/decoding/parser layer, before the
                declared controls (which see an already-parsed {text}) can inspect it.
  mixed         the construction intentionally spans more than one of the above, or cases
                within a subfamily require different declarations.

The scoped exception handler (C3) is cross-cutting: it may shape a response, but it is never
listed in `controls_targeted` and never attributed as causal coverage.

This module only *declares*. It reads no results and imports nothing from analysis/endpoint.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Optional

from contract import COVERAGE_CLASSES, ContractError
from attacks import metadata as md

_DEFAULT_MAP_PATH = Path(__file__).with_name("coverage_map.json")


def default_map_path() -> Path:
    return _DEFAULT_MAP_PATH


def coverage_map_sha256(path: Optional[Path] = None) -> str:
    """SHA-256 of the coverage map file bytes as committed."""
    path = Path(path) if path is not None else _DEFAULT_MAP_PATH
    return hashlib.sha256(path.read_bytes()).hexdigest()


def load_coverage_map(path: Optional[Path] = None) -> dict:
    path = Path(path) if path is not None else _DEFAULT_MAP_PATH
    with path.open(encoding="utf-8") as handle:
        cmap = json.load(handle)
    _validate_map(cmap)
    return cmap


def _validate_map(cmap: dict) -> None:
    if "coverage_map_version" not in cmap:
        raise ContractError("coverage_map.json: missing coverage_map_version")
    for subfamily, decl in cmap.get("subfamilies", {}).items():
        _validate_declaration(subfamily, decl)
    for attack_id, decl in cmap.get("case_exceptions", {}).items():
        _validate_declaration(attack_id, decl)


def _validate_declaration(key: str, decl: dict) -> None:
    cls = decl.get("coverage_class")
    if cls not in COVERAGE_CLASSES:
        raise ContractError(f"coverage_map.json: {key!r} has unknown coverage_class {cls!r}")
    for control in decl.get("controls_targeted", []):
        if control not in md.CONTROLS:
            raise ContractError(
                f"coverage_map.json: {key!r} has unknown control {control!r}"
            )
    if not decl.get("coverage_rationale"):
        raise ContractError(f"coverage_map.json: {key!r} is missing a coverage_rationale")
    # in_scope must name a control; not_targeted/out_of_scope must not; mixed may.
    if cls == "in_scope" and not decl.get("controls_targeted"):
        raise ContractError(f"coverage_map.json: {key!r} is in_scope but names no control")
    if cls in ("not_targeted", "out_of_scope") and decl.get("controls_targeted"):
        raise ContractError(
            f"coverage_map.json: {key!r} is {cls} but names controls {decl['controls_targeted']}"
        )


def resolve_declaration(attack_id: str, subfamily: str, cmap: dict) -> dict:
    """
    Resolve one case's coverage declaration. Per-case exception wins over subfamily.
    An unknown/missing mapping is an ERROR -- it never silently becomes 'unknown'.
    """
    exception = cmap.get("case_exceptions", {}).get(attack_id)
    if exception is not None:
        return exception
    decl = cmap.get("subfamilies", {}).get(subfamily)
    if decl is None:
        raise ContractError(
            f"no coverage declaration for subfamily {subfamily!r} (attack {attack_id!r}). "
            "Every generated case must resolve to a declaration; add it to coverage_map.json."
        )
    return decl


def stamp_manifest(cmap: Optional[dict] = None, *, only_suite: str = md.SUITE_CORE) -> int:
    """
    Stamp coverage onto every registered case in the given suite, in place, from the map.

    Called by build_suite after building, so the manifest that write_manifest dumps carries
    the coverage declaration. Fails loudly if any case's subfamily is unmapped. Returns the
    number of cases stamped. Idempotent: re-running yields identical values.
    """
    if cmap is None:
        cmap = load_coverage_map()
    version = cmap["coverage_map_version"]
    stamped = 0
    for attack_id, meta in md.manifest().items():   # values are live references
        if meta.suite_id != only_suite:
            continue
        decl = resolve_declaration(attack_id, meta.subfamily, cmap)
        meta.coverage_class = decl["coverage_class"]
        meta.controls_targeted = list(decl.get("controls_targeted", []))
        meta.coverage_rationale = decl["coverage_rationale"]
        meta.coverage_map_version = version
        stamped += 1
    return stamped


def build_historical_overlay(historical_manifest_path: Path, cmap: Optional[dict] = None) -> dict:
    """
    Build an attack_id-keyed coverage overlay for a PRESERVED historical manifest, WITHOUT
    touching the archived file. The overlay records its own later creation time and hashes;
    the classification is explicitly *not* historically pre-declared.
    """
    historical_manifest_path = Path(historical_manifest_path)
    if cmap is None:
        cmap = load_coverage_map()
    with historical_manifest_path.open(encoding="utf-8") as handle:
        historical = json.load(handle)

    entries: dict[str, dict] = {}
    for attack_id, meta in historical.items():
        subfamily = meta.get("subfamily")
        if subfamily is None:
            raise ContractError(
                f"historical manifest entry {attack_id!r} has no subfamily to resolve"
            )
        decl = resolve_declaration(attack_id, subfamily, cmap)
        entries[attack_id] = {
            "coverage_class": decl["coverage_class"],
            "controls_targeted": list(decl.get("controls_targeted", [])),
            "coverage_rationale": decl["coverage_rationale"],
        }
    return {
        "_overlay": {
            "note": (
                "Coverage overlay authored AFTER the historical run. The classification is "
                "NOT historically pre-declared; it is applied later from coverage_map.json. "
                "The archived raw manifest is unchanged."
            ),
            "coverage_map_version": cmap["coverage_map_version"],
            "coverage_map_sha256": coverage_map_sha256(),
            "source_manifest_path": str(historical_manifest_path).replace("\\", "/"),
            "source_manifest_sha256": hashlib.sha256(
                historical_manifest_path.read_bytes()
            ).hexdigest(),
        },
        "coverage_by_attack_id": entries,
    }


def write_historical_overlay(historical_manifest_path: Path, out_path: Path,
                             cmap: Optional[dict] = None) -> dict:
    overlay = build_historical_overlay(historical_manifest_path, cmap)
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as handle:
        json.dump(overlay, handle, indent=2, ensure_ascii=False)
        handle.write("\n")
    return overlay
